take out save artifact for sciops images

diff --git a/.github/.staging_workflows/anchored_sciops_docker_images.yaml b/.github/.staging_workflows/anchored_sciops_docker_images.yaml
--- a/.github/.staging_workflows/anchored_sciops_docker_images.yaml
+++ b/.github/.staging_workflows/anchored_sciops_docker_images.yaml
@@ -95,52 +95,19 @@ jobs:
           ## Build image
           docker-compose -f docker-compose-codebook_env.yaml build
           
-          cd ../
-          docker save \
-            -o image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar \
-            "registry.vathes.com/sciops/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}"
-          gzip -S ".gz" image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar
-      - name: Add codebook env image archive to Artifact
-        uses: actions/upload-artifact@v2
-        with: 
-          name: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
-            -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
-          path: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
-            -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          !!merge <<: *$STAGE-retention
-    outputs:
-      repo_name: ${{steps.compile_env.outputs.repo_name}}
-  publish_env_image:
-    !!merge <<: *$STAGE-if
-    needs: [build_env_image]
-    runs-on: ubuntu-latest
-    env:
-      JHUB_VER: ${{inputs.jhub_ver}}
-      PY_VER: ${{inputs.py_ver}}
-      DIST: ${{inputs.dist}}
-      WORKFLOW_VERSION: ${{inputs.workflow_version}}
-    steps:
-      - name: Fetch image archive from Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-            -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
-      - name: Upload image archive to Release
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-        with:
-          upload_url: ${{inputs.release_upload_url}}
-          asset_path: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-            -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          asset_name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-            -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          asset_content_type: application/gzip
-      - name: Load image archive to docker
-        run: |
-          ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
-          docker load \
-            -i "image-codebook-${{needs.build_env_image.outputs.repo_name}}-jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+          # cd ../
+          # docker save \
+          #   -o image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar \
+          #   "registry.vathes.com/sciops/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}"
+          # gzip -S ".gz" image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar
+      # - name: Add codebook env image archive to Artifact
+      #   uses: actions/upload-artifact@v2
+      #   with: 
+      #     name: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
+      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+      #     path: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
+      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+      #     !!merge <<: *$STAGE-retention
       - name: Login to vathes Registry
         uses: docker/login-action@v1
         !!merge <<: *docker-login
@@ -155,6 +122,53 @@ jobs:
                   && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
                   && docker push "${IMAGE}:latest" \
               || echo "skipping 'latest' tag..."
+    outputs:
+      repo_name: ${{steps.compile_env.outputs.repo_name}}
+  # publish_env_image:
+  #   !!merge <<: *$STAGE-if
+  #   needs: [build_env_image]
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     JHUB_VER: ${{inputs.jhub_ver}}
+  #     PY_VER: ${{inputs.py_ver}}
+  #     DIST: ${{inputs.dist}}
+  #     WORKFLOW_VERSION: ${{inputs.workflow_version}}
+  #   steps:
+  #     - name: Fetch image archive from Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+  #     - name: Upload image archive to Release
+  #       uses: actions/upload-release-asset@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+  #       with:
+  #         upload_url: ${{inputs.release_upload_url}}
+  #         asset_path: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_content_type: application/gzip
+  #     - name: Load image archive to docker
+  #       run: |
+  #         ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
+  #         docker load \
+  #           -i "image-codebook-${{needs.build_env_image.outputs.repo_name}}-jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #     - name: Login to vathes Registry
+  #       uses: docker/login-action@v1
+  #       !!merge <<: *docker-login
+  #     - name: Push image
+  #       run: |
+  #         export IMAGE=registry.vathes.com/sciops/codebook-${{needs.build_env_image.outputs.repo_name}}
+  #         export TAG=jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
+  #         docker push "${IMAGE}:${TAG}"
+  #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
+  #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+  #         [ "$PY_VER" == "3.8" ] && [ "$DISTRO" == "alpine" ] \
+  #                 && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
+  #                 && docker push "${IMAGE}:latest" \
+  #             || echo "skipping 'latest' tag..."
       
   ## Build/Publish standard worker
   build_worker_image:
@@ -186,46 +200,14 @@ jobs:
             -o image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar \
             "registry.vathes.com/${{github.repository_owner}}/standard-${REPO_NAME}:py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}"
           gzip -S ".gz" image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar
-      - name: Add standard worker image archive to Artifact
-        uses: actions/upload-artifact@v2
-        with: 
-          name: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
-            -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
-          path: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
-            -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          !!merge <<: *$STAGE-retention
-    outputs:
-      repo_name: ${{steps.compile_worker.outputs.repo_name}}
-  publish_worker_image:
-    !!merge <<: *$STAGE-if
-    needs: [build_worker_image]
-    runs-on: ubuntu-latest
-    env:
-      PY_VER: ${{inputs.py_ver}}
-      DIST: ${{inputs.dist}}
-      WORKFLOW_VERSION: ${{inputs.workflow_version}}
-    steps:
-      - name: Fetch image archive from Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-            -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
-      - name: Upload image archive to Release
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-        with:
-          upload_url: ${{inputs.release_upload_url}}
-          asset_path: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-            -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          asset_name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-            -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-          asset_content_type: application/gzip
-      - name: Load image archive to docker
-        run: |
-          ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
-          docker load \
-            -i "image-standard-${{needs.build_worker_image.outputs.repo_name}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+      # - name: Add standard worker image archive to Artifact
+      #   uses: actions/upload-artifact@v2
+      #   with: 
+      #     name: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
+      #       -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+      #     path: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
+      #       -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+      #     !!merge <<: *$STAGE-retention
       - name: Login to vathes Registry
         uses: docker/login-action@v1
         !!merge <<: *docker-login
@@ -240,4 +222,50 @@ jobs:
                   && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
                   && docker push "${IMAGE}:latest" \
               || echo "skipping 'latest' tag..."
+    outputs:
+      repo_name: ${{steps.compile_worker.outputs.repo_name}}
+  # publish_worker_image:
+  #   !!merge <<: *$STAGE-if
+  #   needs: [build_worker_image]
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     PY_VER: ${{inputs.py_ver}}
+  #     DIST: ${{inputs.dist}}
+  #     WORKFLOW_VERSION: ${{inputs.workflow_version}}
+  #   steps:
+  #     - name: Fetch image archive from Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+  #     - name: Upload image archive to Release
+  #       uses: actions/upload-release-asset@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+  #       with:
+  #         upload_url: ${{inputs.release_upload_url}}
+  #         asset_path: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_content_type: application/gzip
+  #     - name: Load image archive to docker
+  #       run: |
+  #         ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
+  #         docker load \
+  #           -i "image-standard-${{needs.build_worker_image.outputs.repo_name}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #     - name: Login to vathes Registry
+  #       uses: docker/login-action@v1
+  #       !!merge <<: *docker-login
+  #     - name: Push image
+  #       run: |
+  #         export IMAGE=registry.vathes.com/${{github.repository_owner}}/standard-${{needs.build_worker_image.outputs.repo_name}}
+  #         export TAG=py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
+  #         docker push "${IMAGE}:${TAG}"
+  #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
+  #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+  #         [ "$PY_VER" == "3.8" ] && [ "$DISTRO" == "alpine" ] \
+  #                 && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
+  #                 && docker push "${IMAGE}:latest" \
+  #             || echo "skipping 'latest' tag..."
       
