refactor: :recycle: remove "v" attached to version so that other tags, branches, refs can be used.

diff --git a/.github/workflows/sciops_docker_images.yaml b/.github/workflows/sciops_docker_images.yaml
--- a/.github/workflows/sciops_docker_images.yaml
+++ b/.github/workflows/sciops_docker_images.yaml
@@ -1,5 +1,5 @@
 #### For running in Github Action
-  ##### Need to manually add deploy private key to 
+  ##### Need to manually add deploy private key to
   ##### Settings->Secrets->Actions: REGISTRY_USERNAME REGISTRY_PASSWORD
 #### For running locally using act
   ##### create a .secrets file just like .env, for example:
@@ -59,16 +59,16 @@ jobs:
 
           # cd ../
           # docker save \
-          #   -o image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar \
-          #   "registry.vathes.com/sciops/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}"
-          # gzip -S ".gz" image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar
+          #   -o image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}.tar \
+          #   "registry.vathes.com/sciops/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}"
+          # gzip -S ".gz" image-codebook-${REPO_NAME}-jhub${JHUB_VER}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}.tar
       # - name: Add codebook env image archive to Artifact
       #   uses: actions/upload-artifact@v2
-      #   with: 
+      #   with:
       #     name: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
-      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}"
       #     path: "image-codebook-${{steps.compile_env.outputs.repo_name}}\
-      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+      #       -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
       #     !!merge <<: *prod-retention
       - name: Login to vathes Registry
         uses: docker/login-action@v1
@@ -79,7 +79,7 @@ jobs:
       - name: Push image
         run: |
           export IMAGE=registry.vathes.com/sciops/codebook-${{github.repository}}
-          export TAG=jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
+          export TAG=jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}
           docker push "${IMAGE}:${TAG}"
           docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
           docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
@@ -103,7 +103,7 @@ jobs:
   #       uses: actions/download-artifact@v2
   #       with:
   #         name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}"
   #     - name: Upload image archive to Release
   #       uses: actions/upload-release-asset@v1
   #       env:
@@ -111,22 +111,22 @@ jobs:
   #       with:
   #         upload_url: ${{inputs.release_upload_url}}
   #         asset_path: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
   #         asset_name: "image-codebook-${{needs.build_env_image.outputs.repo_name}}\
-  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #           -jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
   #         asset_content_type: application/gzip
   #     - name: Load image archive to docker
   #       run: |
   #         ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
   #         docker load \
-  #           -i "image-codebook-${{needs.build_env_image.outputs.repo_name}}-jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+  #           -i "image-codebook-${{needs.build_env_image.outputs.repo_name}}-jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
   #     - name: Login to vathes Registry
   #       uses: docker/login-action@v1
   #       !!merge <<: *docker-login
   #     - name: Push image
   #       run: |
   #         export IMAGE=registry.vathes.com/sciops/codebook-${{needs.build_env_image.outputs.repo_name}}
-  #         export TAG=jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
+  #         export TAG=jhub${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}
   #         docker push "${IMAGE}:${TAG}"
   #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
   #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
@@ -146,14 +146,32 @@ jobs:
       - uses: actions/checkout@v2
       - id: compile_worker
         name: Compile codebook worker image
-        run: "## Get build info\ncd ./docker\nexport REPO_NAME=$(echo ${{github.repository}} | awk -F\\/ '{print $2}')\necho \"::set-output name=repo_name::${REPO_NAME}\"\nexport REPO_OWNER=${{github.repository_owner}}\n\necho \"${{secrets.RAW_DEPLOY_KEY}}\" | base64 -di >> ${REPO_NAME}-deploy.pem\nchmod 400 ${REPO_NAME}-deploy.pem\nexport DEPLOY_KEY=${REPO_NAME}-deploy.pem\n\n## Build image\ndocker-compose -f docker-compose-standard_worker.yaml build \n\n# cd ../\n# docker save \\\n#   -o image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar \\\n#   \"registry.vathes.com/${{github.repository_owner}}/standard-${REPO_NAME}:py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}\"\n# gzip -S \".gz\" image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}.tar\n"
+        run: |
+          ## Get build info
+          cd ./docker
+          export REPO_NAME=$(echo ${{github.repository}} | awk -F\/ '{print $2}')
+          echo "::set-output name=repo_name::${REPO_NAME}"
+          export REPO_OWNER=${{github.repository_owner}}
+
+          echo "${{secrets.RAW_DEPLOY_KEY}}" | base64 -di >> ${REPO_NAME}-deploy.pem
+          chmod 400 ${REPO_NAME}-deploy.pem
+          export DEPLOY_KEY=${REPO_NAME}-deploy.pem
+
+          ## Build image
+          docker-compose -f docker-compose-standard_worker.yaml build
+
+          # cd ../
+          # docker save \
+          #   -o image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}.tar \
+          #   "registry.vathes.com/${{github.repository_owner}}/standard-${REPO_NAME}:py${PY_VER}-${DIST}-${WORKFLOW_VERSION}"
+          # gzip -S ".gz" image-standard-${REPO_NAME}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}.tar
       # - name: Add standard worker image archive to Artifact
       #   uses: actions/upload-artifact@v2
-      #   with: 
+      #   with:
       #     name: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
-      #       -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
+      #       -py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}"
       #     path: "image-standard-${{steps.compile_worker.outputs.repo_name}}\
-      #       -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
+      #       -py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
       #     !!merge <<: *prod-retention
       - name: Login to vathes Registry
         uses: docker/login-action@v1
@@ -164,7 +182,7 @@ jobs:
       - name: Push image
         run: |
           export IMAGE=registry.vathes.com/${{github.repository_owner}}/standard-${{github.repository}}
-          export TAG=py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
+          export TAG=py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}
           docker push "${IMAGE}:${TAG}"
           docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
           docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
@@ -174,47 +192,47 @@ jobs:
               || echo "skipping 'latest' tag..."
     outputs:
       repo_name: ${{steps.compile_worker.outputs.repo_name}}
-      # publish_worker_image:
-      #   !!merge <<: *prod-if
-      #   needs: [build_worker_image]
-      #   runs-on: ubuntu-latest
-      #   env:
-      #     PY_VER: ${{inputs.py_ver}}
-      #     DIST: ${{inputs.dist}}
-      #     WORKFLOW_VERSION: ${{inputs.workflow_version}}
-      #   steps:
-      #     - name: Fetch image archive from Artifact
-      #       uses: actions/download-artifact@v2
-      #       with:
-      #         name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-      #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}"
-      #     - name: Upload image archive to Release
-      #       uses: actions/upload-release-asset@v1
-      #       env:
-      #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-      #       with:
-      #         upload_url: ${{inputs.release_upload_url}}
-      #         asset_path: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-      #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-      #         asset_name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
-      #           -py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-      #         asset_content_type: application/gzip
-      #     - name: Load image archive to docker
-      #       run: |
-      #         ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
-      #         docker load \
-      #           -i "image-standard-${{needs.build_worker_image.outputs.repo_name}}-py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}.tar.gz"
-      #     - name: Login to vathes Registry
-      #       uses: docker/login-action@v1
-      #       !!merge <<: *docker-login
-      #     - name: Push image
-      #       run: |
-      #         export IMAGE=registry.vathes.com/${{github.repository_owner}}/standard-${{needs.build_worker_image.outputs.repo_name}}
-      #         export TAG=py${{env.PY_VER}}-${{env.DIST}}-v${{env.WORKFLOW_VERSION}}
-      #         docker push "${IMAGE}:${TAG}"
-      #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
-      #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
-      #         [ "$PY_VER" == "3.8" ] && [ "$DISTRO" == "alpine" ] \
-      #                 && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
-      #                 && docker push "${IMAGE}:latest" \
-      #             || echo "skipping 'latest' tag..."
+  # publish_worker_image:
+  #   !!merge <<: *prod-if
+  #   needs: [build_worker_image]
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     PY_VER: ${{inputs.py_ver}}
+  #     DIST: ${{inputs.dist}}
+  #     WORKFLOW_VERSION: ${{inputs.workflow_version}}
+  #   steps:
+  #     - name: Fetch image archive from Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}"
+  #     - name: Upload image archive to Release
+  #       uses: actions/upload-release-asset@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+  #       with:
+  #         upload_url: ${{inputs.release_upload_url}}
+  #         asset_path: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_name: "image-standard-${{needs.build_worker_image.outputs.repo_name}}\
+  #           -py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
+  #         asset_content_type: application/gzip
+  #     - name: Load image archive to docker
+  #       run: |
+  #         ## If you local machine is not the same as the "runs-on", this step would fail: invalid tar header
+  #         docker load \
+  #           -i "image-standard-${{needs.build_worker_image.outputs.repo_name}}-py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}.tar.gz"
+  #     - name: Login to vathes Registry
+  #       uses: docker/login-action@v1
+  #       !!merge <<: *docker-login
+  #     - name: Push image
+  #       run: |
+  #         export IMAGE=registry.vathes.com/${{github.repository_owner}}/standard-${{needs.build_worker_image.outputs.repo_name}}
+  #         export TAG=py${{env.PY_VER}}-${{env.DIST}}-${{env.WORKFLOW_VERSION}}
+  #         docker push "${IMAGE}:${TAG}"
+  #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}--${GITHUB_SHA:0:7}"
+  #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+  #         [ "$PY_VER" == "3.8" ] && [ "$DISTRO" == "alpine" ] \
+  #                 && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
+  #                 && docker push "${IMAGE}:latest" \
+  #             || echo "skipping 'latest' tag..."
